name : Test solutions
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-dotnet@v3
                with:
                    dotnet-version: '7.0.x'
            -   uses: actions/setup-java@v4
                with:
                    distribution: 'microsoft'
                    java-version: '11'
            -   uses: ts-graphviz/setup-graphviz@v2
            -   name: Check dependencies
                run: |
                    dotnet --info
                    java -version
                    dot -V

